# Generated by Django 5.1.6 on 2025-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabom", "0002_like_unique_user_article_like"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="like",
            name="unique_user_article_like",
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(fields=("user", "article"), name="unique_user_article"),
        ),
    ]
